import { integer, pgTable, uuid, varchar, timestamp, boolean } from 'drizzle-orm/pg-core';

export const supabaseUserTable = pgTable('users', {
  id: uuid().primaryKey(),
  instance_id: uuid().notNull(),
  aud: varchar({ length: 255 }).notNull(),
  role: varchar({ length: 255 }).notNull(),
  email: varchar({ length: 255 }).notNull(),
  encrypted_password: varchar({ length: 255 }).notNull(),
  email_confirmed_at: timestamp(),
  invited_at: timestamp(),
  confirmation_token: varchar({ length: 255 }),
  confirmation_sent_at: timestamp(),
  recovery_token: varchar({ length: 255 }),
  recovery_sent_at: timestamp(),
  email_change_token: varchar({ length: 255 }),
  email_change: timestamp(),
  email_change_sent_at: timestamp(),
  last_sign_in_at: timestamp(),
  raw_app_meta_data: varchar({ length: 255 }),
  raw_user_meta_data: varchar({ length: 255 }),
  is_super_admin: boolean().notNull(),
  created_at: timestamp().notNull(),
  updated_at: timestamp().notNull(),
  phone: varchar({ length: 255 }),
  phone_confirmed_at: timestamp(),
  phone_change: timestamp(),
  phone_change_token: varchar({ length: 255 }),
  phone_change_sent_at: timestamp(),
  confirmed_at: timestamp(),
  email_change_token_current: varchar({ length: 255 }),
  email_change_confirm_status: integer().notNull(),
  banned_until: timestamp(),
  reauthentication_token: varchar({ length: 255 }),
  reauthentication_sent_at: timestamp(),
  is_sso_user: boolean().notNull(),
  deleted_at: timestamp(),
});
